### ISSUE TITLE
Fixed Position not kept

### ISSUE THREAD

**Issue by limitx3m** [JByfordRew/BlazorTransitionableRoute#10]
Items with fixed positions are not fixed after a transition.

Removing the animation class in devtools after the animation has finished, such as "animate__fadeInDown", returns items to their normal state.

Suggestions?

**Comment by JByfordRew** [comment]
Thank you for reporting this. I will look into it.

**Comment by limitx3m** [comment]
I'm still investigating, and not much of a CSS guy; however, I was able to relieve my initial problem.

Using animate.css for transitions uses
```
animate-fill-mode: both;
```
This keeps the styling of the animation and overrides other stylings like fixed.

**Comment by JByfordRew** [comment]
Great news. Shall I close the issue? Others will find it here if they have the same problem in future?

**Comment by limitx3m** [comment]
Sure.
