### ISSUE TITLE
Possible to transition between multiple layouts?

### ISSUE THREAD

**Issue by lucaswalter** [JByfordRew/BlazorTransitionableRoute#4]
I'm working on an application right now and would like to use different layouts for when the user is going through Onboarding steps or has completed them and are in the main application.

I noticed the docs have you specify a single `MainLayout` that will be used throughout the application. Is it possible to use transactions between multiple?

```
    <Found Context="routeData">
        <LayoutView Layout="@typeof(MainLayout)">
            <TransitionableRoutePrimary RouteData="@routeData" ForgetStateOnTransition="false">
                <TransitionableRouteView DefaultLayout="@typeof(MyViewLayout)" />
            </TransitionableRoutePrimary>
            <TransitionableRouteSecondary RouteData="@routeData" ForgetStateOnTransition="false">
                <TransitionableRouteView DefaultLayout="@typeof(MyViewLayout)" />
            </TransitionableRouteSecondary>
        </LayoutView>
    </Found>
```

If not, how can we approach using a mix of 'Transitionable' and non-transitionable layouts? One though was to get the page type and see if it implements some `ITransitionableLayoutComponent` interface through reflection, but wanted to check if there was a way already built-in to handle this.

Your help is much appreciated!

**Comment by JByfordRew** [comment]
Many thanks for this suggestion. A new scenario indeed. Not sure how animation would suite transitions between different layouts. I will definitely find a solution, hopefully to your clearly defined example, but it may take a little time. Very interested in solving it though. Good news is most solutions end up quite elegant in the end.

**Comment by lucaswalter** [comment]
Wow, thanks for the quick response! That would be incredibly useful for our use-case. Here's a bit more detail on what we are hoping to accomplish so you have more context:

Our application uses multiple sets of layouts such as `AccountLayout` / `OnboardingWelcomeLayout` / `OnboardingQuestionLayout` depending  on the page a user is on.

Ideally, we would like to be able to provide a transition from `OnboardingWelcomeLayout` -> `OnboardingQuestionLayout` after a user clicks a button.

---

Additionally, it seems right now the transition configuration in `App.razor` needs to be duplicated multiple times in order to work with multiple layouts. From the consumers perspective, this would be nice to only configure once generically and avoid a nasty switch statement with copy-pasted code.

Is there anything we can do in the meantime to help tackle this? We are very interested in using BlazorTransitionableRoute, hooking into routing seemed to be the most stable/configurable approach.

Thanks!

**Comment by lucaswalter** [comment]
Here's also an example of the big switch/if-else code we are trying to avoid in `App.razor` to configure transitions:

```
            @if (routeData.PageType.IsAssignableFrom(typeof(IAccountPage)))
            {
                // Checking if page is an IAccountPage

                <LayoutView Layout="@typeof(AccountLayout)">
                    <TransitionableRoutePrimary RouteData="@routeData" ForgetStateOnTransition="false">
                        <TransitionableRouteView DefaultLayout="@typeof(TransitionLayout)"/>
                    </TransitionableRoutePrimary>
                    <TransitionableRouteSecondary RouteData="@routeData" ForgetStateOnTransition="false">
                        <TransitionableRouteView DefaultLayout="@typeof(TransitionLayout)"/>
                        </TransitionableRouteSecondary>   
                  </LayoutView>

            }
            else if (routeData.PageType.IsAssignableFrom(typeof(IOnboardingPage)))
            {
                // Note: Would like to avoid having to copy-paste this if check for each type

                <LayoutView Layout="@typeof(OnboardingWelcomeLayout)">
                    <TransitionableRoutePrimary RouteData="@routeData" ForgetStateOnTransition="false">
                        <TransitionableRouteView DefaultLayout="@typeof(TransitionLayout)"/>
                    </TransitionableRoutePrimary>
                    <TransitionableRouteSecondary RouteData="@routeData" ForgetStateOnTransition="false">
                        <TransitionableRouteView DefaultLayout="@typeof(TransitionLayout)"/>
                    </TransitionableRouteSecondary>
                </LayoutView>
            }
            else
            {
                // Regular non-transitionable route

                <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            }
```

**Comment by JByfordRew** [comment]
I found this while searching for a solution, for your reference.
https://github.com/dotnet/aspnetcore/issues/26122

Also general guidance on layouts
https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0

They may help me identify a solution.

**Comment by JByfordRew** [comment]
My initial thoughts looking at this are to first consider the nested layouts capability where your layouts would include a `@layout yourTransitionableRouteView` (in your case `TransitionLayout`) to specify a containing layout. This would also provide the optimality you need as well as keeping the original behaviour of RouteViews. It could also mean a simplification on the `App.razor` changes needed for this component library.

**Comment by JByfordRew** [comment]
Here is the change to `App.razor` showing the `MainLayout` being redintroduced back at the `RouteView` level

```
<Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
    <Found Context="routeData">
        <TransitionableRoutePrimary RouteData="@routeData" ForgetStateOnTransition="true">
            <TransitionableRouteView DefaultLayout="@typeof(MainLayout)" />
        </TransitionableRoutePrimary>
        <TransitionableRouteSecondary RouteData="@routeData" ForgetStateOnTransition="true">
            <TransitionableRouteView DefaultLayout="@typeof(MainLayout)" />
        </TransitionableRouteSecondary>
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```

You can then add `@layout TransitionLayout` to `MainLayout` to complete the code changes.  This is following the nested layouts approach from the Blazor documentation.  I am also assuming that not adding the `@layout TransitionLayout` to your layouts that do not require transitions would result in them being rendered immediately without transitioning.

This does result in my demo performing full page transitions which may be what you want.  If this is not then you will probably need to move the usages of `TransitionableRouteView` component into your own pages or layouts.

I hope this will help you with this issue.  Please provide feedback on how it goes so I may close this issue.  Many thanks.

**Comment by lucaswalter** [comment]
Thank you for the pointer on nested layouts. I was able to get full page transitions working by following your example and by specifying the layout desired on each page. Thank you for the help!

**Comment by JByfordRew** [comment]
Closing until told otherwise.

**Comment by lucaswalter** [comment]
One thing to note (not sure if you got this at all on your end), but I did see quite a considerable performance hit when using this full page approach. I spun the example up again with the blazor wasm template and was getting about a 400ms on input to switch back and forth from /count to /fetchdata

**Comment by JByfordRew** [comment]
I don't think I saw this. Let me know if it becomes an issue.

**Comment by limitx3m** [comment]
Using it this way, without using < LayoutView > in app.razor, leaves a one second gap between Loading and render.
 Suggestions?
