### ISSUE TITLE
AuthorizeRouteView and TransitionableRouteView

### ISSUE THREAD

**Issue by michwroch** [JByfordRew/BlazorTransitionableRoute#5]
Hello,
Anyone know how can I add AuthorizeRouteView to TransitionableRouteView?
Maybe I need create own RouteView ?

**Comment by JByfordRew** [comment]
Hi, thank you for pointing this out. I shall look into how to do this.

**Comment by JByfordRew** [comment]
At first glance it looks like `AuthorizeView` and `RouteView` are composable  so you could make it work, I am assuming, by changing the implementation from the combined `AuthorizeRouteView` to a nested implementation with `AuthorizeView` as the inner. Let us know how it goes. I'll add this to the roadmap to provide an authorise version of transition route view. Hope this helped.

**Comment by michwroch** [comment]
Ok, I created new TransitionableRouteView. It's look like this

````c#
@if (Transition?.RouteData != null)
{
    <CascadingValue Value="Transition">
        <AuthorizeRouteView RouteData="@Transition.RouteData" DefaultLayout="@DefaultLayout"></AuthorizeRouteView>
    </CascadingValue>
}

@code {
    [CascadingParameter]
    public Transition Transition { get; set; }

    [Parameter]
    public Type DefaultLayout { get; set; }
}
````


Probably it's working, but maybe I don't know something. I didn't study your code. Please tell me if this is correct.

**Comment by JByfordRew** [comment]
That looks correct to me. Hope it works. I'll leave this issue open for 7 days unless you say otherwise.

**Comment by JByfordRew** [comment]
Hope your solution worked. Closing issue.

**Comment by keerthirajap** [comment]
Can you please provide details implementation on Program.cs, App.razor for AuthorizeRouteView. I am unable to implement

`
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <NavigationTracker />
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                    @if (!context.User.Identity.IsAuthenticated)
                    {
                        <SignIn />
                    }
                    else
                    {
                        <AccessDenied />
                    }
                </NotAuthorized>
            </AuthorizeRouteView>
        </Found>
        <NotFound>
            <NavigationTracker />
            <LayoutView Layout="@typeof(MainLayout)">
                <PageNotFound />
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
`

**Comment by JByfordRew** [comment]
It seems the [Microsoft.AspNetCore.Components.Authorization](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Authorization) is not compatible with the .net standard 2.1 which the component is currently targeting.  Therefore I will need to create the .NET 6 update first before I can build in the `AuthorizeRouteView` .  I will also the roadmap and hopefully perform these two steps soon.

**Comment by JByfordRew** [comment]
For now I suggest you implement your own `TransitionableAuthorizeRouteView` component in your solution as this https://github.com/JByfordRew/BlazorTransitionableRoute/issues/5#issuecomment-897991942

**Comment by JByfordRew** [comment]
See this commit https://github.com/JByfordRew/BlazorTransitionableRoute/commit/84505f6995657842b1b4a5265a6d09d3df8c85df

**Comment by JByfordRew** [comment]
I will not be building this into the component due to the configurability of your AuthorizeRouteView's. This will have to remain a custom implementation per use case. There is not much code required as shown in the commit above.
