### ISSUE TITLE
Transition sometimes works, sometimes doesn't

### ISSUE THREAD

**Issue by aokocax** [JByfordRew/BlazorTransitionableRoute#6]
First of all, thanks for your hard work. I added the library to my Blazor project (wasm), but transition sometimes works, sometimes doesn't (Pages show suddenly).
I also debug, but unfortunately I couldn't understand why. Any ideas? 

I have 3 views "/","/Form","/Tab" 
![image](https://user-images.githubusercontent.com/1059475/131811414-d1f04815-3f63-4072-a293-e92fd8936609.png)

https://user-images.githubusercontent.com/1059475/131810974-52782209-2187-4ca5-9766-e0a7a8dcfae5.mp4

@code {
    private string transitioningClass => Transition.FirstRender
        ? "" : $"animate__{transitioningEffect()} animate__faster animate__animated";

    private string transitioningEffect()
    {
        if (customTransitions.TryGetValue((TransitionType.fromType, TransitionType.toType), out var custom))
        {
            return Transition.IntoView ? custom.effectIn : custom.effectOut;
        }
        else
        {
            var effect = Transition.IntoView ? "fadeIn" : "fadeOut";
            var direction = Transition.Backwards ? "Up" : "Down";
            var result = effect + direction;
            Console.WriteLine(result);
            return result;
        }
    }

    private Dictionary<(Type from, Type to), (string effectOut, string effectIn)> customTransitions =
        new Dictionary<(Type from, Type to), (string effectOut, string effectIn)>
        {
           
        };
}

Thank you.

**Comment by JByfordRew** [comment]
Hi, many thanks for sharing this in detail. I will have a think. Perhaps I could come your repo and try to diagnose it myself.

**Comment by aokocax** [comment]
Thank you for replying. I have shared the repo with you. 
I think with MAU-Blazor (Xamarin) Transition will become very important to deliver the native experience to mobile app users.

**Comment by JByfordRew** [comment]
It seems like a delay in rendering the content after the transition period has occurred. Perhaps try without transitions and observe if there are rendering delays.

**Comment by JByfordRew** [comment]
I have added this as a roadmap item and will close this issue now and see if a number of other users have the same need.
* Check behaviour for slow loaded pages and handle transition when in ready state or suggest best practice for pages that exhibit this.
