### ISSUE TITLE
AuthorizeRouteData does not work

### ISSUE THREAD

**Issue by kenshintdd** [JByfordRew/BlazorTransitionableRoute#8]
Any idea of how to make it work with authorized/unauthorized routes?
I saw that on roadmap, any chance of being implemented any time soon?

Cheers!

**Comment by JByfordRew** [comment]
Hi please see this closed is first, it may help https://github.com/JByfordRew/BlazorTransitionableRoute/issues/5

**Comment by kenshintdd** [comment]
Hi, thanks, I tried the proposed solution replacing TransitionableRouteView but unfortunatelly didn't work.

**Comment by JByfordRew** [comment]
Okay, I will try to resolve this as soon as I can. I did wait until more than a couple of people mentioned it. Hopefully sort this out soon.

**Comment by kenshintdd** [comment]
Very much appreciated, thanks in advance!

**Comment by JByfordRew** [comment]
It seems the [Microsoft.AspNetCore.Components.Authorization](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Authorization) is not compatible with the .net standard 2.1 which the component is currently targeting.  Therefore I will need to create the .NET 6 update first before I can build in the `AuthorizeRouteView` .  I will also the roadmap and hopefully perform these two steps soon.

**Comment by JByfordRew** [comment]
For now I suggest you implement your own `TransitionableAuthorizeRouteView` component in your solution as this https://github.com/JByfordRew/BlazorTransitionableRoute/issues/5#issuecomment-897991942

**Comment by kenshintdd** [comment]
Okay, thank  you very much for your effort, please let me know when the package is upgraded.

**Comment by JByfordRew** [comment]
See this commit https://github.com/JByfordRew/BlazorTransitionableRoute/commit/84505f6995657842b1b4a5265a6d09d3df8c85df

**Comment by JByfordRew** [comment]
I will not be building this into the component due to the configurability of your AuthorizeRouteView's.  This will have to remain a custom implementation per use case.  There is not much code required as shown in the commit above.  Closing this issue now.
