### ISSUE TITLE
MAUI Blazor Hybrid app on iOS - 'init' was undefined

### ISSUE THREAD

**Issue by peter-bozovic** [JByfordRew/BlazorTransitionableRoute#9]
This error appears when trying to run MAUI Blazor Hybrid iOS app with the BlazorTransitionableRoute library

I was able to fix it by changing these files:

in `jsInterop.js` replace
```
export function init(dotnetHelper, isPrimary) {
```
with
```
window.init = (dotnetHelper, isPrimary) => {
```

and

in `TransitionableRoutePrimary.razor.cs` replace  
```
jsInterop ??= new JsInterop(JSRuntime);
await jsInterop.Init(DotNetObjectReference.Create(this), isActive);

```
with
```
await JSRuntime.InvokeVoidAsync("init", DotNetObjectReference.Create(this), isActive);
```

I don't know how to do pull request of what else this change might break, but it works for me like this for now :)

You can implement if properly if you have means to test it in this environment, or just close the issue and keep it as reference if someone else has the same issue ...

**Comment by JByfordRew** [comment]
Hi, many thanks for reporting this.  I myself have not experimented with MAUI yet so will do as you suggest and leave this for reference and close it.  I'll keep an eye out for more reported issues where a change to the repo may happen.  Many thanks again.

**Comment by JByfordRew** [comment]
Also this try v3.1.0 of this component, the behaviour is the same and may work without needing alteration as the js file has the function declarations as you have provided.

**Comment by JByfordRew** [comment]
Also really interested in how the component performs in MAUI, so please share once happy to.

**Comment by peter-bozovic** [comment]
Hey, it actually works OTB with v3.1 ! :)

The things are looking good for now in terms of performances, but I really had to spend sooo much time to make everything work as it should. What is missing in the library is really the built-in transitions that users can just use without having to build their own. I'm not the expert in any of this, so it took me few days to make the css transitions work, then I had strange issue where annimation was shuttered and spend few more days to find out why and how to fix it, and then I understood that I'll need my own TransitionNavigationManager that would handle which animation to use for the navigation, the backward action etc, that took few more days. I spent almost two weeks to have something usable that could be huge win if library already supported it ...

So the idea is good, the samples are working, but they are too simple for real application needs.
In my use case, I needed to be able to say when navigating from one page to another, if it's comming from left, from right, or from the bottom, or if back navigation is done to do the opposite.

The biggest issue was in setting these transitions in the TransitionLayout. I have the class `navState` that knows which transition should be used for the page comming in and which one for the page comming out, so I had something like this:
```
<div class="transition @(Transition.IntoView ? navState.TransitionIn : navState.TransitionOut)">
```
But with this, the animation was shuttering and it's very difficult to debug animations :)
Until I understood that the issues was in changing the navState properties were they were applied on both TransitionLayouts which applied the new animation on the page that should use the old animation to translate out ...
So I had to do something like this
```
<div class="transition @(Transition.IntoView ? TransitionIn : navState.TransitionOut)">
    @Body
</div>
@code {
    string TransitionIn { get; set; } = "";
 
    protected override void OnInitialized() {
        TransitionIn = navState.TransitionIn;
    }
}
```
I have to store the initial animation when the layout initializes so that I can use it when it goes out and that the original animation is not overridden with the new one.
But I think this works only if the Layouts are created and disposed each time, which is my use case ...

That was my experience until now. Again, for the larger public, it would probably be very useful to have built-in animations and simple way to decide which one to use when navigating between pages. Otherwise most of the users will have to spend a lot of time making their own implementations of something that is quite common and IMO should be supported by the library.

**Comment by JByfordRew** [comment]
Many thanks for your thoughts. As there are so many animation libraries out there, I decided not to provide a default. You should not need to roll your own animations CSS. Sorry to hear you had difficulties in implementing the animations with this library. I've not had other reports of this to date. I will of course consider a common default animation integration at some point. Also many thanks for your detailed notes on your experience with it. Regards.

**Comment by peter-bozovic** [comment]
I had to remove the library from my project for now :(

It works in Debug build mode, but in Release build for the iOS, the app starts with white screen ...
And this time I don't have the Console output where I can see the error.
After reverting to the basic RouteView the app works

I'll try to investigate more, but first I have to figure out how to get JS error messages within my app to be able to log them.
Then to find the solution how to fix if possible ...

**Comment by peter-bozovic** [comment]
So after many months, I was able to investigate more and found a workaround !

Error that was appearing only in iOS applications compiled for release:
> iOS error
> Unable to set property 'Transition' on object of type 'MyApp.Shared.TransitionLayout'. The error was: Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_TransitionLayout_Transition (MyApp.Shared.TransitionLayout,BlazorTransitionableRoute.Transition)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

So I have found this similar issue with the hint on the workaround:
https://github.com/dotnet/runtime/issues/74015

And the solution for me was to add the folowing into the project configuration:
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
	...
	<EnableAssemblyILStripping>false</EnableAssemblyILStripping>
	<UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

After which the app was able to run on iOS in release mode ! :-)
